3.1

diff --git a/gcc/build_gcc b/gcc/build_gcc
--- a/gcc/build_gcc
+++ b/gcc/build_gcc
@@ -6,7 +6,9 @@ set -x
 # -arch arguments are different than configure arguments. We need to
 # translate them.
 
-TRANSLATE_ARCH="sed -e s/ppc/powerpc/ -e s/i386/i686/"
+TRANSLATE_ARCH="sed -e s/ppc/powerpc/ -e s/i386/i686/ -e s/ppc64/powerpc64/"
+TRANSLATE_TARGETS="sed -e s/ppc/powerpc/ -e s/i386/i686/ -e s/x86_64// \
+  -e s/powerpc64// -e s/ppc64//"
 
 # Build GCC the "Apple way".
 # Parameters:
@@ -20,7 +22,7 @@ HOSTS=`echo $1 | $TRANSLATE_ARCH `
 # compilers will generate code for.  If the current machine isn't in
 # the list, a compiler for it will get built anyway, but won't be
 # installed.
-TARGETS=`echo $2 | $TRANSLATE_ARCH`
+TARGETS=`echo $2 | $TRANSLATE_TARGETS`
 
 # The GNU makefile target ('bootstrap' by default).
 BOOTSTRAP=${BOOTSTRAP-bootstrap}
@@ -70,17 +72,18 @@ VERS=`sed -n -e '/version_string/s/.*\"\([^ \"]*\)[ \"].*/\1/p' \
 MAJ_VERS=`echo $VERS | sed 's/\([0-9]*\.[0-9]*\)[.-].*/\1/'`
 
 # This is the default architecture for i386 configurations.
-I386_CPU="--with-arch=nocona --with-tune=generic"
+I386_CPU="--with-arch=apple --with-tune=generic"
+
+# APPLE LOCAL begin ARM ARM_CONFIGFLAGS
+# For ARM, grab all system files from an SDK.
+ARM_SYSROOT="/Developer/SDKs/Extra"
+ARM_CONFIGFLAGS="--with-sysroot=\"$ARM_SYSROOT\""
+# APPLE LOCAL end ARM ARM_CONFIGFLAGS
 
 # This is the libstdc++ version to use.
 LIBSTDCXX_VERSION=4.0.0
 
-# Sniff to see if we can do ppc64 building.
-DARWIN_VERS=8
-if [ x"`file /usr/lib/crt1.o | grep 'architecture ppc64'`" == x ]; then
-    DARWIN_VERS=7
-fi
-
+DARWIN_VERS=`uname -r | sed 's/\..*//'`
 echo DARWIN_VERS = $DARWIN_VERS
 
 # If the user has CC set in their environment unset it now
@@ -139,6 +142,10 @@ if [ \! -f Makefile ]; then
    `if [ $BUILD = i686 ] ; then echo $I386_CPU ; fi` \
    --host=$BUILD-apple-darwin$DARWIN_VERS --target=$BUILD-apple-darwin$DARWIN_VERS || exit 1
 fi
+# Unset RC_DEBUG_OPTIONS because it causes the bootstrap to fail.
+# Also keep unset for cross compilers so that the cross built libraries are
+# comparable to the native built libraries.
+unset RC_DEBUG_OPTIONS
 make $MAKEFLAGS $BOOTSTRAP CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
 make $MAKEFLAGS html CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
 make $MAKEFLAGS DESTDIR=$DIR/dst-$BUILD-$BUILD install-gcc install-target \
@@ -174,15 +181,18 @@ done
 PATH=$DIR/bin:$PATH
 
 # Build the cross-compilers, using the compiler we just built.
-for t in $TARGETS ; do
+for t in `echo $TARGETS $HOSTS | sort -u`; do
  if [ $t != $BUILD ] ; then
   mkdir -p $DIR/obj-$BUILD-$t $DIR/dst-$BUILD-$t || exit 1
    cd $DIR/obj-$BUILD-$t || exit 1
    if [ \! -f Makefile ]; then
+# APPLE LOCAL begin ARM ARM_CONFIGFLAGS
     $SRC_DIR/configure $CONFIGFLAGS --enable-werror-always \
      `if [ $t = i686 ] ; then echo $I386_CPU ; fi` \
+     `if [ $t = 'arm' ] ; then echo $ARM_CONFIGFLAGS ; fi` \
       --program-prefix=$t-apple-darwin$DARWIN_VERS- \
       --host=$BUILD-apple-darwin$DARWIN_VERS --target=$t-apple-darwin$DARWIN_VERS || exit 1
+# APPLE LOCAL end ARM ARM_CONFIGFLAGS
    fi
    make $MAKEFLAGS all CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
    make $MAKEFLAGS DESTDIR=$DIR/dst-$BUILD-$t install-gcc install-target \
@@ -215,10 +225,13 @@ for h in $HOSTS ; do
       fi
 
       if [ \! -f Makefile ]; then
+# APPLE LOCAL begin ARM ARM_CONFIGFLAGS
         $SRC_DIR/configure $CONFIGFLAGS \
 	  `if [ $t = i686 ] ; then echo $I386_CPU ; fi` \
+	  `if [ $t = 'arm' ] && [ $h != 'arm' ] ; then echo $ARM_CONFIGFLAGS ; fi` \
           --program-prefix=$pp \
           --host=$h-apple-darwin$DARWIN_VERS --target=$t-apple-darwin$DARWIN_VERS || exit 1
+# APPLE LOCAL end ARM ARM_CONFIGFLAGS
       fi
       make $MAKEFLAGS all-gcc CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
       make $MAKEFLAGS DESTDIR=$DIR/dst-$h-$t install-gcc \
@@ -237,7 +250,7 @@ cd $DEST_DIR || exit 1
 rm -rf * || exit 1
 
 # HTML documentation
-HTMLDIR="/Developer/ADC Reference Library/documentation/DeveloperTools"
+HTMLDIR="/Developer/Documentation/DocSets/com.apple.ADC_Reference_Library.DeveloperTools.docset/Contents/Resources/Documents/documentation/DeveloperTools"
 mkdir -p ".$HTMLDIR" || exit 1
 cp -Rp $DIR/obj-$BUILD-$BUILD/gcc/HTML/* ".$HTMLDIR/" || exit 1
 
@@ -266,7 +279,6 @@ for t in $TARGETS ; do
   done
   ln -s ../../../../bin/as .$DL/as
   ln -s ../../../../bin/ld .$DL/ld
-  ln -s ../../../../bin/libtool .$DL/libtool
 done
 
 # bin
@@ -297,31 +309,20 @@ for t in $TARGETS ; do
     .$DEST_ROOT/lib/gcc || exit 1
 done
 
-SHARED_LIBS="libgcc_s.1.dylib libgcc_s.10.4.dylib libgcc_s.10.5.dylib"
-
-for l in $SHARED_LIBS ; do
-  CANDIDATES=()
-  for t in $TARGETS ; do
-    if [ -e $DIR/dst-$t-$t$DEST_ROOT/lib/$l ] ; then
-      CANDIDATES[${#CANDIDATES[*]}]=$DIR/dst-$t-$t$DEST_ROOT/lib/$l
-    fi
-  done
-  if [ -L ${CANDIDATES[0]} ] ; then
-    ln -s `readlink ${CANDIDATES[0]}` .$DEST_ROOT/lib/$l || exit 1
-  else
-    lipo -output .$DEST_ROOT/lib/$l -create "${CANDIDATES[@]}" || exit 1
-  fi
-done
-
-# For backwards compatibility link libgcc_s.1.dylib to the 64-bit versions.
-ln -s libgcc_s.1.dylib .$DEST_ROOT/lib/libgcc_s_ppc64.1.dylib
-ln -s libgcc_s.1.dylib .$DEST_ROOT/lib/libgcc_s_x86_64.1.dylib
-
+# APPLE LOCAL begin ARM armv6 dylib
 for t in $TARGETS ; do
-  ln -s ../../../libstdc++.6.dylib \
-    .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib \
-    || exit 1
+  if [ "$t" == 'arm' ] ; then
+    cp -p $ARM_SYSROOT/usr/lib/libstdc++.6.dylib \
+      .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib \
+      || exit 1
+  else
+    cp -p /usr/lib/libstdc++.6.dylib \
+      .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib \
+      || exit 1
+  fi
+  strip -x -c .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib || exit 1
 done
+# APPLE LOCAL end ARM armv6 dylib
 
 # include
 HEADERPATH=$DEST_ROOT/include/gcc/darwin/$MAJ_VERS
@@ -346,20 +347,6 @@ for h in `echo *.h` ; do
     done
   fi
 done
-mkdir -p $DEST_DIR$HEADERPATH/machine
-for h in `echo */*.h` ; do
-  if [ ! -f /usr/include/$h -o -L /usr/include/$h ] ; then
-    cp -R $h $DEST_DIR$HEADERPATH/$h || exit 1
-    for t in $TARGETS ; do
-      THEADERPATH=$DEST_DIR$DEST_ROOT/lib/gcc/${t}-apple-darwin$DARWIN_VERS/$VERS/include
-      mkdir -p $THEADERPATH/machine
-      # In fixincludes/fixinc.in we created this file...  always link for now
-      [ -f /disable/$THEADERPATH/$h ] || \
-        ln -f -s ../../../../../../include/gcc/darwin/$MAJ_VERS/$h $THEADERPATH/$h || \
-        exit 1
-    done
-  fi
-done
 
 # Add extra man page symlinks for 'c++' and for arch-specific names.
 MDIR=$DEST_DIR$DEST_ROOT/share/man/man1
@@ -371,28 +358,32 @@ for t in $TARGETS ; do
       || exit 1
 done
 
+# APPLE LOCAL begin ARM native compiler support
 # Build driver-driver using fully-named drivers
 for h in $HOSTS ; do
-    $DEST_DIR$DEST_ROOT/bin/$h-apple-darwin$DARWIN_VERS-gcc-$VERS                          \
-	$ORIG_SRC_DIR/gcc/config/darwin-driver.c                               \
+    $DIR/dst-$BUILD-$h$DEST_ROOT/bin/$h-apple-darwin$DARWIN_VERS-gcc-$VERS     \
+	$ORIG_SRC_DIR/driverdriver.c                               \
 	-DPDN="\"-apple-darwin$DARWIN_VERS-gcc-$VERS\""                                    \
 	-DIL="\"$DEST_ROOT/bin/\"" -I  $ORIG_SRC_DIR/include                   \
 	-I  $ORIG_SRC_DIR/gcc -I  $ORIG_SRC_DIR/gcc/config                     \
 	-liberty -L$DIR/dst-$BUILD-$h$DEST_ROOT/lib/                           \
 	-L$DIR/dst-$BUILD-$h$DEST_ROOT/$h-apple-darwin$DARWIN_VERS/lib/                    \
         -L$DIR/obj-$h-$BUILD/libiberty/                                        \
+        -L$DIR/obj-$h-$h/libiberty/                                        \
 	-o $DEST_DIR/$DEST_ROOT/bin/tmp-$h-gcc-$MAJ_VERS || exit 1
 
-    $DEST_DIR$DEST_ROOT/bin/$h-apple-darwin$DARWIN_VERS-gcc-$VERS                          \
-	$ORIG_SRC_DIR/gcc/config/darwin-driver.c                               \
+    $DIR/dst-$BUILD-$h$DEST_ROOT/bin/$h-apple-darwin$DARWIN_VERS-gcc-$VERS                 \
+	$ORIG_SRC_DIR/driverdriver.c                               \
 	-DPDN="\"-apple-darwin$DARWIN_VERS-g++-$VERS\""                                    \
 	-DIL="\"$DEST_ROOT/bin/\"" -I  $ORIG_SRC_DIR/include                   \
 	-I  $ORIG_SRC_DIR/gcc -I  $ORIG_SRC_DIR/gcc/config                     \
 	-liberty -L$DIR/dst-$BUILD-$h$DEST_ROOT/lib/                           \
 	-L$DIR/dst-$BUILD-$h$DEST_ROOT/$h-apple-darwin$DARWIN_VERS/lib/                    \
         -L$DIR/obj-$h-$BUILD/libiberty/                                        \
+        -L$DIR/obj-$h-$h/libiberty/                                        \
 	-o $DEST_DIR/$DEST_ROOT/bin/tmp-$h-g++-$MAJ_VERS || exit 1
 done
+# APPLE LOCAL end ARM native compiler support
 
 lipo -output $DEST_DIR/$DEST_ROOT/bin/gcc-$MAJ_VERS -create \
   $DEST_DIR/$DEST_ROOT/bin/tmp-*-gcc-$MAJ_VERS || exit 1
@@ -405,18 +396,21 @@ ln -f $DEST_DIR/$DEST_ROOT/bin/g++-$MAJ_VERS $DEST_DIR/$DEST_ROOT/bin/c++-$MAJ_V
 rm $DEST_DIR/$DEST_ROOT/bin/tmp-*-gcc-$MAJ_VERS || exit 1
 rm $DEST_DIR/$DEST_ROOT/bin/tmp-*-g++-$MAJ_VERS || exit 1
 
-
 ########################################
-# Save the source files and objects needed for debugging
+# Create SYM_DIR with information required for debugging.
 
 cd $SYM_DIR || exit 1
 
 # Clean out SYM_DIR in case -noclean was passed to buildit.
 rm -rf * || exit 1
 
-# Save executables and libraries.
+# Generate .dSYM files
+find $DEST_DIR -perm -0111 \! -name fixinc.sh \
+    \! -name mkheaders -type f -print | xargs -n 1 -P ${SYSCTL} dsymutil
+
+# Save .dSYM files and .a archives
 cd $DEST_DIR || exit 1
-find . \( -perm -0111 -or -name \*.a -or -name \*.dylib \) -type f -print \
+find . \( -path \*.dSYM/\* -or -name \*.a \) -print \
   | cpio -pdml $SYM_DIR || exit 1
 # Save source files.
 mkdir $SYM_DIR/src || exit 1
@@ -424,15 +418,14 @@ cd $DIR || exit 1
 find obj-* -name \*.\[chy\] -print | cpio -pdml $SYM_DIR/src || exit 1
 
 ########################################
-# Strip the executables and libraries
-find $DEST_DIR -perm -0111 \! -name \*.dylib \! -name fixinc.sh \
-    \! -name mkheaders -type f -print \
+# Remove debugging information from DEST_DIR.
+
+find $DEST_DIR -perm -0111 \! -name fixinc.sh \
+    \! -name mkheaders \! -name libstdc++.dylib -type f -print \
   | xargs strip || exit 1
-find $DEST_DIR \( -name \*.a -or -name \*.dylib \) \
-    \! -name libgcc_s.10.*.dylib -type f -print \
-  | xargs strip -SX || exit 1
-find $DEST_DIR -name \*.a -type f -print \
-  | xargs ranlib || exit 1
+find $DEST_DIR -name \*.a -print | xargs strip -SX || exit 1
+find $DEST_DIR -name \*.a -print | xargs ranlib || exit 1
+find $DEST_DIR -name \*.dSYM -print | xargs rm -r || exit 1
 chgrp -h -R wheel $DEST_DIR
 chgrp -R wheel $DEST_DIR
 
diff --git a/gcc/gcc/configure b/gcc/gcc/configure
--- a/gcc/gcc/configure
+++ b/gcc/gcc/configure
@@ -8708,13 +8708,15 @@ vax-*-*)
     stage1_cflags="-J"
   fi
   ;;
-powerpc-*-darwin*)
+# APPLE LOCAL begin mainline
+powerpc*-*-darwin*)
   # The spiffy cpp-precomp chokes on some legitimate constructs in GCC
   # sources; use -no-cpp-precomp to get to GNU cpp.
   # Apple's GCC has bugs in designated initializer handling, so disable
   # that too.
   stage1_cflags="-no-cpp-precomp -DHAVE_DESIGNATED_INITIALIZERS=0"
   ;;
+# APPLE LOCAL end mainline
 esac
 
 
@@ -11726,6 +11728,90 @@ fi
 done
 
 
+# APPLE LOCAL begin mainline 2006-06-02 4508814
+
+for ac_func in sigaltstack
+do
+  ac_tr_decl=`echo "HAVE_DECL_$ac_func" | $as_tr_cpp`
+echo "$as_me:$LINENO: checking whether $ac_func is declared" >&5
+echo $ECHO_N "checking whether $ac_func is declared... $ECHO_C" >&6
+if eval "test \"\${gcc_cv_have_decl_$ac_func+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#undef $ac_tr_decl
+#define $ac_tr_decl 1
+
+#include "ansidecl.h"
+#include "system.h"
+#include <signal.h>
+
+
+int
+main ()
+{
+#ifndef $ac_func
+char *(*pfn) = (char *(*)) $ac_func ;
+#endif
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "gcc_cv_have_decl_$ac_func=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "gcc_cv_have_decl_$ac_func=no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+if eval "test \"`echo '$gcc_cv_have_decl_'$ac_func`\" = yes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6 ; cat >>confdefs.h <<_ACEOF
+#define $ac_tr_decl 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6 ; cat >>confdefs.h <<_ACEOF
+#define $ac_tr_decl 0
+_ACEOF
+
+fi
+
+done
+
+# APPLE LOCAL end mainline 2006-06-02 4508814
+
 # More time-related stuff.
 echo "$as_me:$LINENO: checking for struct tms" >&5
 echo $ECHO_N "checking for struct tms... $ECHO_C" >&6
@@ -12164,6 +12250,64 @@ if test "$host_xm_file" != "$build_xm_file"; then
 		done
 	fi
 fi
+
+# APPLE LOCAL begin mainline 2006-06-02 4508814
+case ${host} in
+  powerpc*-*-darwin*)
+    echo "$as_me:$LINENO: checking whether mcontext_t fields have underscores" >&5
+echo $ECHO_N "checking whether mcontext_t fields have underscores... $ECHO_C" >&6
+if test "${gcc_cv_mcontext_underscores+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+#include <ucontext.h>
+int main() { mcontext_t m; if (m->ss.srr0) return 0; return 0; }
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  gcc_cv_mcontext_underscores=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+gcc_cv_mcontext_underscores=yes
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_mcontext_underscores" >&5
+echo "${ECHO_T}$gcc_cv_mcontext_underscores" >&6
+      if test $gcc_cv_mcontext_underscores = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAS_MCONTEXT_T_UNDERSCORES
+_ACEOF
+
+      fi
+    ;;
+esac
+# APPLE LOCAL end mainline 2006-06-02 4508814
 
 # ---------
 # Threading
@@ -12805,14 +12949,15 @@ for f in $build_xm_file; do
   esac
 done
 
-# Define macro CROSS_COMPILE in compilation if this is a cross-compiler.
+# Define macro CROSS_DIRECTORY_STRUCTURE in compilation if this is a
+# cross-compiler which does not use the native headers and libraries.
 # Also use all.cross instead of all.internal and adjust SYSTEM_HEADER_DIR.
 CROSS=
 ALL=all.internal
 SYSTEM_HEADER_DIR='$(NATIVE_SYSTEM_HEADER_DIR)'
 if test x$host != x$target
 then
-	CROSS="-DCROSS_COMPILE"
+	CROSS="-DCROSS_DIRECTORY_STRUCTURE"
 	ALL=all.cross
 	SYSTEM_HEADER_DIR='$(CROSS_SYSTEM_HEADER_DIR)'
 	case "$host","$target" in
diff --git a/gdb/src/gdb/configure b/gdb/src/gdb/configure
--- a/gdb/src/gdb/configure
+++ b/gdb/src/gdb/configure
@@ -1570,6 +1570,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
+  --disable-arch-for-exec disable use of arch for exec
   --disable-nls           do not use Native Language Support
   --disable-gdbcli        disable command-line interface (CLI)
   --disable-gdbmi         disable machine-interface (MI)
@@ -1581,6 +1582,11 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --disable-carbon-framework
+                          disable Carbon framework use even when available
+  --disable-debug-symbols-framework
+                          disable DebugSymbols framework use even when
+                          available
   --enable-build-warnings Enable build-time compiler warnings if gcc is used
   --enable-gdb-build-warnings Enable GDB specific build-time compiler warnings if gcc is used
   --enable-sim            Link gdb with simulator
@@ -2065,9 +2071,7 @@ fi
 
   { echo "$as_me:$LINENO: result: $USE_MAINTAINER_MODE" >&5
 echo "${ECHO_T}$USE_MAINTAINER_MODE" >&6; }
-
-
-if test $USE_MAINTAINER_MODE = yes; then
+   if test $USE_MAINTAINER_MODE = yes; then
   MAINTAINER_MODE_TRUE=
   MAINTAINER_MODE_FALSE='#'
 else
@@ -3796,10 +3800,19 @@ esac
 
 
 case "$host" in
+  arm-apple-*)
+    # No 64 bit exceptions for Apple ARM
+    { echo "$as_me:$LINENO: checking whether we can use 64 bit mach exceptions" >&5
+echo $ECHO_N "checking whether we can use 64 bit mach exceptions... $ECHO_C" >&6; }
+    MACH_EXC_SERVER_PREFACE=
+    { echo "$as_me:$LINENO: result: (disabled!) no" >&5
+echo "${ECHO_T}(disabled!) no" >&6; }
+
+    ;;
   *-apple-darwin* | *-apple-maocsx*)
     { echo "$as_me:$LINENO: checking whether we can use 64 bit mach exceptions" >&5
 echo $ECHO_N "checking whether we can use 64 bit mach exceptions... $ECHO_C" >&6; }
-    if test -r "/usr/include/mach/mach_exc.defs"; then
+    if test -r "$SDKROOT/usr/include/mach/mach_exc.defs"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_64_BIT_MACH_EXCEPTIONS 1
@@ -3818,6 +3831,10 @@ echo "${ECHO_T}no" >&6; }
 esac
 
 case "$host" in
+  arm-apple-*)
+    # We need to turn off arch for exec for now as it doesn't support launching
+    # a specified architecture in a universal mach file.
+    ;;
   *-apple-darwin* | *-apple-macosx*)
     { echo "$as_me:$LINENO: checking whether posix_spawn supports SETEXEC" >&5
 echo $ECHO_N "checking whether posix_spawn supports SETEXEC... $ECHO_C" >&6; }
@@ -3862,29 +3879,51 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+    { echo "$as_me:$LINENO: result: $gdb_cv_posix_spawn" >&5
+echo "${ECHO_T}$gdb_cv_posix_spawn" >&6; }
+
     if test $gdb_cv_posix_spawn = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_POSIX_SPAWN 1
 _ACEOF
 
+
+      # Check whether --enable-arch-for-exec was given.
+if test "${enable_arch_for_exec+set}" = set; then
+  enableval=$enable_arch_for_exec; case $enableval in
+          yes | no)
+            enable_arch_exec="$enableval" ;;
+          *)
+            { { echo "$as_me:$LINENO: error: bad value '$enableval' for --disable-arch-for-exec" >&5
+echo "$as_me: error: bad value '$enableval' for --disable-arch-for-exec" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      	esac
+else
+  enable_arch_exec=yes
+fi
+
+
       { echo "$as_me:$LINENO: checking whether we should use arch for exec" >&5
 echo $ECHO_N "checking whether we should use arch for exec... $ECHO_C" >&6; }
-      if test -r "/usr/bin/arch"; then
+      if test x"$enable_arch_exec" = xyes; then
+        if test -r "/usr/bin/arch"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_ARCH_FOR_EXEC 1
 _ACEOF
 
-        { echo "$as_me:$LINENO: result: yes" >&5
+          { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-      else
-        { echo "$as_me:$LINENO: result: no" >&5
+        else
+          { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
+        fi
+      else
+        { echo "$as_me:$LINENO: result: (disabled) no" >&5
+echo "${ECHO_T}(disabled) no" >&6; }
       fi
     fi
-    { echo "$as_me:$LINENO: result: $gdb_cv_posix_spawn" >&5
-echo "${ECHO_T}$gdb_cv_posix_spawn" >&6; }
 ;;
 esac
 
@@ -8461,7 +8500,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8464 "configure"' > conftest.$ac_ext
+  echo '#line 8503 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10605,11 +10644,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10608: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10647: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10612: \$? = $ac_status" >&5
+   echo "$as_me:10651: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10873,11 +10912,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10876: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10915: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10880: \$? = $ac_status" >&5
+   echo "$as_me:10919: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10977,11 +11016,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11019: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10984: \$? = $ac_status" >&5
+   echo "$as_me:11023: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13285,7 +13324,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13288 "configure"
+#line 13327 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13385,7 +13424,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13388 "configure"
+#line 13427 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15721,11 +15760,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15724: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15763: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15728: \$? = $ac_status" >&5
+   echo "$as_me:15767: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15825,11 +15864,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15828: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15867: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15832: \$? = $ac_status" >&5
+   echo "$as_me:15871: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17395,11 +17434,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17398: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17437: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17402: \$? = $ac_status" >&5
+   echo "$as_me:17441: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17499,11 +17538,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17502: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17541: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17506: \$? = $ac_status" >&5
+   echo "$as_me:17545: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19697,11 +19736,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19700: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19739: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19704: \$? = $ac_status" >&5
+   echo "$as_me:19743: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19965,11 +20004,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19968: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20007: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19972: \$? = $ac_status" >&5
+   echo "$as_me:20011: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20069,11 +20108,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20072: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20111: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20076: \$? = $ac_status" >&5
+   echo "$as_me:20115: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -33032,41 +33071,91 @@ esac
 
 case "$host" in
   *-apple-darwin* | *-apple-macos*)
-  { echo "$as_me:$LINENO: checking for Carbon framework" >&5
+    # Check whether --enable-carbon-framework was given.
+if test "${enable_carbon_framework+set}" = set; then
+  enableval=$enable_carbon_framework; case $enableval in
+      yes | no)
+        enable_carbon_framework="$enableval" ;;
+      *)
+        { { echo "$as_me:$LINENO: error: bad value '$enableval' for --disable-carbon-framework" >&5
+echo "$as_me: error: bad value '$enableval' for --disable-carbon-framework" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+  enable_carbon_framework=no
+fi
+
+
+    { echo "$as_me:$LINENO: checking for Carbon framework" >&5
 echo $ECHO_N "checking for Carbon framework... $ECHO_C" >&6; }
-  if test -d /System/Library/Frameworks/Carbon.framework
-  then
-    CARBON_LIBS="-framework Carbon"
-    { echo "$as_me:$LINENO: result: yes" >&5
+    if test x"$enable_carbon_framework" = xyes; then
+      if test -d "$SDKROOT/System/Library/Frameworks/Carbon.framework"
+      then
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_CARBON_FRAMEWORK 1
+_ACEOF
+
+        CARBON_LIBS="-framework Carbon"
+        { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-  else
-    { echo "$as_me:$LINENO: result: no" >&5
+      else
+        { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-  fi
-  ;;
+      fi
+    else
+      { echo "$as_me:$LINENO: result: (disabled) no" >&5
+echo "${ECHO_T}(disabled) no" >&6; }
+    fi
+    ;;
 esac
+
 
 
 case "$host" in
+  arm-apple-*)
+  # We won't be using DebugSymbols.framework to locate dSYM files for ARM yet.
+  ;;
   *-apple-darwin* | *-apple-macos*)
-  { echo "$as_me:$LINENO: checking for DebugSymbols framework" >&5
+    # Check whether --enable-debug-symbols-framework was given.
+if test "${enable_debug_symbols_framework+set}" = set; then
+  enableval=$enable_debug_symbols_framework; case $enableval in
+      yes | no)
+        enable_debug_symbols_framework="$enableval" ;;
+      *)
+        { { echo "$as_me:$LINENO: error: bad value '$enableval' for --disable-debug-symbols-framework" >&5
+echo "$as_me: error: bad value '$enableval' for --disable-debug-symbols-framework" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+  enable_debug_symbols_framework=yes
+fi
+
+
+    { echo "$as_me:$LINENO: checking for DebugSymbols framework" >&5
 echo $ECHO_N "checking for DebugSymbols framework... $ECHO_C" >&6; }
-  if test -d /System/Library/PrivateFrameworks/DebugSymbols.framework
-  then
+    if test x"$enable_debug_symbols_framework" = xyes; then
+      if test -d "$SDKROOT/System/Library/PrivateFrameworks/DebugSymbols.framework"
+      then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_DEBUG_SYMBOLS_FRAMEWORK 1
+#define USE_DEBUG_SYMBOLS_FRAMEWORK 1
 _ACEOF
 
-    DEBUG_SYMBOLS_LIBS="-F/System/Library/PrivateFrameworks -framework DebugSymbols"
-    { echo "$as_me:$LINENO: result: yes" >&5
+        DEBUG_SYMBOLS_LIBS="-F/System/Library/PrivateFrameworks -framework DebugSymbols"
+        { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-  else
-    { echo "$as_me:$LINENO: result: no" >&5
+      else
+        { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-  fi
+      fi
+    else
+      { echo "$as_me:$LINENO: result: (disabled) no" >&5
+echo "${ECHO_T}(disabled) no" >&6; }
+    fi
   ;;
 esac
+
 
 
 # APPLE LOCAL: Use the pre-conformant headers/functions so we stand a
