2.2

diff --git a/gcc_os/build_gcc b/gcc_os/build_gcc
--- a/gcc_os/build_gcc
+++ b/gcc_os/build_gcc
@@ -46,7 +46,17 @@ build_gcc_main()
       echo "The temporary directory '$TEMP' does not exist!"
       exit 1
     fi
-    
+
+    # Make sure that GCC 4 never gets used.
+    # <rdar://problem/4280381> Chardonnay: gcc_os fails to build
+    rm -rf $TEMP/build_gcc.$$ && mkdir /tmp/build_gcc.$$ || exit 1
+    PATH=$TEMP/build_gcc.$$:$PATH
+    for FILE in gcc g++ cpp c++ gcov
+        do ln -s /usr/bin/$FILE-3.3 $TEMP/build_gcc.$$/$FILE
+        ln -s /usr/bin/$FILE-3.3 $TEMP/build_gcc.$$/$FILE-4.0
+    done
+    ln -s /usr/bin/gcc-3.3 $TEMP/build_gcc.$$/cc
+
     #
     # The host on which we are running on now (what machine is being used to build
     # compiler)...
@@ -222,6 +232,8 @@ build_gcc_main()
     #
     # Install HTML documentation
     $nc install_html
+
+    rm -rf $TEMP/build_gcc.$$
 
     if [ ! "$n" ]; then
     	box_title "build_gcc script completed at `date +'%x %X %Z'`"
@@ -1543,7 +1555,7 @@ install_fat()
 		    libtool_cmd="libtool -o $fat_file -arch_only ppc $sym/$host/lib/ppc/libstdc++.clean.a"
 		fi
 
-		libtool_cmd="mkdir -p $fat/$privatelib && $libtool_cmd -dynamic -L$fat/$lib -lSystem -lgcc -install_name $privatelib/$LIBSTDCPP_DYLIB -v -current_version 1 -compatibility_version 1"
+		libtool_cmd="mkdir -p $fat/$privatelib && $libtool_cmd -dynamic -L$fat/$lib -lSystem -lmx -lgcc -install_name $privatelib/$LIBSTDCPP_DYLIB -v -current_version 1 -compatibility_version 1"
 	    fi
 
 	    # libtool makes libraries fat...
